Completed homework 1
MrKekMan04/skblab-javacourse pull request #1
Opened 2024-03-02 15:32 UTC by MrKekMan04

2024-03-03 11:53 UTC, QuenbKing requested changes
В общих чертах работа отличная, и всё сделано хорошо, но нужно исправить ошибку связанную с выбором неправильной аннотации.

2024-03-03 11:53 UTC, QuenbKing commented on src/main/java/ru/vitaliyefimov/skblab/entity/FooImpl2.java
> +@Configuration
Нужно добавить аннотацию  Component вместо Configuration

2024-03-03 11:55 UTC, MrKekMan04 commented on src/main/java/ru/vitaliyefimov/skblab/entity/FooImpl2.java
> +@Configuration
Да, поспешил и выбрал неправильную аннотацию. Исправил!

2024-03-03 11:55 UTC, QuenbKing approved these changes

2024-03-14 05:14 UTC, nemoguigrat commented on src/main/java/ru/vitaliyefimov/skblab/entity/ClassWithFoo1.java
> +    private final Foo fooImpl1;
Все же лучше стараться использовать осмысленные названия для классов и сервисов без цифр в названии. Также Impl в названии оправдан, когда у нас только одна реализация интерфейса

2024-03-14 05:14 UTC, nemoguigrat commented on src/main/java/ru/vitaliyefimov/skblab/config/DIConfiguration.java
> +public class DIConfiguration {
создавать бины через `@Configuration` можно, но это тоже должно быть оправдано. Случаи когда надо:
- когда используем классы из сторонних библиотек
- когда нет возможности внедрить бины через `@Autowired` или конструктор
- когда приходится для одного бина указывать несколько названий или указать методы жизненного цикла (это все параметры аннотации, можно тут почитать https://docs.spring.io/spring-framework/reference/core/beans/java/bean-annotation.html)
- если нужно создать бины одного и того же класса, но с разными параметрами (или например разными типа дженериков)

В остальных случаях лучше использовать специальные аннотации @Service или @Component

2024-03-14 08:12 UTC, MrKekMan04 commented on src/main/java/ru/vitaliyefimov/skblab/config/DIConfiguration.java
> +public class DIConfiguration {
Тут я просто показал, что можно внедрять и через конфигурацию. В проекте также есть создание и через мета-аннотации Component

2024-03-14 08:13 UTC, MrKekMan04 commented on src/main/java/ru/vitaliyefimov/skblab/entity/ClassWithFoo1.java
> +    private final Foo fooImpl1;
В задании не было сказано какую именно логику реализовывать, поэтому выбрал абстракцию.

2024-03-14 08:37 UTC, nemoguigrat commented on src/main/java/ru/vitaliyefimov/skblab/entity/ClassWithFoo1.java
> +    private final Foo fooImpl1;
Да, я понимаю, что задание в вакууме, но стиля именования следует придерживаться

2024-03-14 08:37 UTC, nemoguigrat commented on src/main/java/ru/vitaliyefimov/skblab/config/DIConfiguration.java
> +public class DIConfiguration {
Я это увидел, но здесь все же это должно быть оправдано. Можешь как раз один из кейсов, которые я выше привел здесь попробовать реализовать (какой либо класс из сторонней библиотеки например оформить как бин или прописать классам какие либо параметры)

2024-03-23 10:39 UTC, closed without merging